#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.


composer global require drush/drush
drush status
# last version
#composer global update
#php composer global require drush/drush:7.1.0
#composer global require drush/drush:7.1.0

#echo $COMPOSER_HOME
#echo $COMPOSER_BIN_DIR
#echo $COMPOSER_VENDOR_DIR

