#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# last version
#composer global update
composer global require drush/drush:7.1.0

mv php/* .
mv php/.gitignore .
rmdir php

